SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE FAVORITE;
TRUNCATE TABLE LINE_STATION;
TRUNCATE TABLE STATION;
TRUNCATE TABLE LINE;
TRUNCATE TABLE MEMBER;

ALTER TABLE LINE
    ALTER COLUMN LINE_ID RESTART WITH 1;
ALTER TABLE STATION
    ALTER COLUMN STATION_ID RESTART WITH 1;
ALTER TABLE MEMBER
    ALTER COLUMN MEMBER_ID RESTART WITH 1;
ALTER TABLE LINE_STATION
    ALTER COLUMN LINE_STATION_ID RESTART WITH 1;
ALTER TABLE FAVORITE
    ALTER COLUMN FAVORITE_ID RESTART WITH 1;

SET REFERENTIAL_INTEGRITY TRUE;
